setting a mobile version skeleton of my portfolio
gasangw/My-portfolio pull request #2
Opened 2022-04-22 09:56 UTC by gasangw

- This portfolio only includes the toolbar and headline sections.
- in the index.html I added a toolbar that I labeled "nav" and the headline section.
- The styles.css file styles only the toolbar and headline sections only with the use of flexbox tools. 
- added an images folder that contained all the images I used.

2022-04-22 13:02 UTC, zainsadaqat requested changes
# Hello @gasangw  😃 😄 

You're doing a great job on your project. We're proud of you. Good job so far! 


There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
  ✅  Correct use of Github Flow
  ✅  No linter errors

## Required Changes ♻️

[Required Design]
<img width="356" alt="Screen Shot 2022-04-22 at 5 59 01 PM" src="https://user-images.githubusercontent.com/83048208/164719025-2b394d44-e99d-47d1-9ae2-4b3ec5612965.png">

[Your Design]

- [x] Navbar is not matching with the required Figma design. Please remove the unnecessary nav items( Portfolio, About, Contact) it's for the Desktop version.
- [x] Background image is missing. Please export the background image from the Figma design and use it in your project.
- [x] Please add hamburger menu icon in the navbar

<img width="316" alt="Screen Shot 2022-04-22 at 5 59 57 PM" src="https://user-images.githubusercontent.com/83048208/164719146-1458412a-445e-46b6-a6a8-11cf16d07ec9.png">


_Check the comments under the review._


<img src="https://media0.giphy.com/media/QvMIzHw30MmMAqvOeo/giphy.gif"/>

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding! 👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-22 13:02 UTC, zainsadaqat commented on index.html
> +  </nav><br><br><br><br>
Please use padding or margin instead of <br/> tags because it's hard to inspect while debugging.

2022-04-22 13:02 UTC, zainsadaqat commented on index.html
> +  <i class="individual-1">My Logo</i>
Please use `<a>` tag for the logo because it can be used to go to the home page in the future.

2022-04-22 13:02 UTC, zainsadaqat commented on index.html
> +  <i class="individual-4">Contact</i>
Please remove the nav items for now As it's not required. Instead, use the hamburger icon as you can see in the Figma design. you can export this icon from Figma and use this in your project. 

<img width="81" alt="Screen Shot 2022-04-22 at 5 51 40 PM" src="https://user-images.githubusercontent.com/83048208/164717867-d1545aab-4c83-4945-b7e1-34cd8988f9c8.png">

2022-04-22 13:02 UTC, zainsadaqat commented on index.html
> +          <h1 class="items item2">Glad to see you !</h1>
There should be only one `<h1>` tag in an HTML document. As you already have used one for your main heading that's why you can replace it with hx tags (hx = h2 ... h6).

2022-04-22 13:02 UTC, zainsadaqat commented on index.html
> +            </div>
Please use `<ul>` `<li>` tags to display a list of items like these social media links.
#### Example:
```
<ul>
 <li>
  <a href="#"><img src="" alt="" /></a>
 </li>
....
....
</ul>
```

2022-04-22 13:02 UTC, zainsadaqat commented on styles.css
> +nav {
Kindly use CSS classes to style the HTML elements instead of directly applying styles on HTML tags because CSS classes are reusable.

2022-04-22 13:02 UTC, zainsadaqat commented on styles.css
> +  background-size: contain;
There is no need to use a fixed width, and height also please remove the overflow-y property because the web will do this automatically for you.

2022-04-22 15:33 UTC, danmainah requested changes
Hi @gasangw , 

Great work on making the changes requested by a previous reviewer 👏  👏 👏
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
✔️ No linter errors
✔️ Github flow was correctly used
✔️  Good PR and Description


 # Required Changes ♻️

- [ ] Please make sure your design matches the design given,see the comparison below for better understanding.

MOBILE MENU

Figma Design          |  Your design     
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/61408860/164745585-de9e4b57-65a1-4f6a-81a9-db5897ae727f.png)|![image](https://user-images.githubusercontent.com/61408860/164745352-bb6cd06f-d95e-4453-9dd7-7a7e4660248f.png)

- [ ] Kindly make you don't have branch conflicts, you can use this[ GitHub documentation](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github) on how to fix merge conflicts,

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-22 17:25 UTC, RolandM99 requested changes
Hi @gasangw, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-22 17:25 UTC, RolandM99 commented on styles.css
> +  align-content: flex-start;
- [ ] As requested by the previous reviewer, Make sure that your design fits correctly the original design from the [Figma template](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1).
The font, color, style, margin, and with of each element should be the same as on the Figma template.
- [ ] Also, you have to add a background image to your headline section as you can see on the Figma template. here below is a background image you can use:
![header-shapes mobile](https://user-images.githubusercontent.com/71874425/164762736-9b9fbece-f97b-4a05-a318-c4a7bfb89213.png)
- [ ] Make sure that the size(width) of your `p` tag with class="items item3" is the same as the design from the Figma template.
- Kindly, implement all the requested changes, ensure that your design is similar to the Figma template, and then request a re-review.

2022-04-23 00:10 UTC, mmsesay requested changes
Hi @gasangw, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-23 00:10 UTC, mmsesay commented on styles.css
> +  color: #091e42;
- [ ] The current colour should be `#344563` instead of `#091e42`. Please update it and set the font-weight to `400`

2022-04-23 00:10 UTC, mmsesay commented on styles.css
> +  color: rgb(49, 163, 201);
- [ ] This content `LET'S CONNECT` colour should be `#7F8CFF` instead of `rgb(49, 163, 201)` Please update this also.

2022-04-23 00:10 UTC, mmsesay commented on styles.css
> +}
- [ ] You did well adding the background image as suggested by the previous reviewer. However, its margin is a bit too much making your design differs a bit from the figma design.

Your Design | Figma Design |
:---------------:|:-------------------:|
![a1](https://user-images.githubusercontent.com/39523312/164836553-3c5c4ae5-ba05-4e69-a84d-6f6e72790a99.png)| ![a2](https://user-images.githubusercontent.com/39523312/164836557-3fb0651c-82e5-4aeb-b1fb-001f713bca6c.png)

2022-04-23 06:35 UTC, gasangw commented on index.html
> +  </nav><br><br><br><br>
@zainsadaqat
I added and made the necessary changes but I don't know why on GitHub you are seeing a different work from the one I have
![Screenshot (381)](https://user-images.githubusercontent.com/99269832/164883170-5548302c-be6b-4db2-8f20-7ff54054d078.png)
.

2022-04-23 10:34 UTC, Temmarie approved these changes
## Status: Approved :heavy_check_mark:

### Hi @gasangw    ! :wave: :wave:

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better and prevent this issue from coming up in future milestones as it was not completely resolved._

You can also consider:

- [ OPTIONAL] Kindly make sure to adjust the margins in the background image as recommended by the previous reviewer as that issue is still present. 

 _See images below_

**Original** | **Your project**
  ----------- | -----------
![a2](https://user-images.githubusercontent.com/39523312/164836557-3fb0651c-82e5-4aeb-b1fb-001f713bca6c.png) | ![image](https://user-images.githubusercontent.com/49621279/164890924-3c01bfbf-bbcb-42c5-8ce5-81438c9b7018.png)


#### Cheers and Happy coding!👏👏👏

#### Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-23 15:54 UTC, merged